(() => {
'use strict';
const $=id=>document.getElementById(id),G=window.TrussGeometry;
function tz(g,c){const lines=['ТЗ СВАРЩИКУ — АРОЧНЫЙ НАВЕС','Размер навеса: '+G.fmt(g.widthPostsM,2)+' × '+G.fmt(c.lengthM,2)+' м','Ширина фермы: '+G.mm(g.widthM)+' мм','Подъём дуги: '+G.mm(g.riseM)+' мм','Высота фермы: '+G.mm(g.heightM)+' мм','Пояса: '+g.chordProfile,'Решётка: '+g.webProfile,'Ферм: '+c.trussCount+' шт.','Линий лаг: '+c.lagLines,'Новых столбов: '+c.newPosts+' шт.','Продольных балок изготовить: '+c.beamCount+' шт.','', 'P1 Верхний пояс: '+G.mm(g.topCircle.length)+' мм × 1','P2 Нижний пояс: '+G.mm(g.lowerTotalM)+' мм × 1','V Торцевые стойки: '+G.mm(g.endPostM)+' мм × 2'];g.diagonals.forEach(d=>lines.push('D'+d.index+': '+G.mm(d.lengthM)+' мм, угол оси '+G.fmt(d.angleDeg,1)+'°'));lines.push('','Перед серийной резкой изготовить одну контрольную ферму по шаблону.');return lines.join('\n');}
function download(){const g=window.__TRUSS_CURRENT;if(!g?.ok)return;const source=window.TrussDrawing.serialize($('trussSvg')),blob=new Blob([source],{type:'image/svg+xml;charset=utf-8'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download='ferma-'+G.mm(g.widthM)+'-'+G.mm(g.riseM)+'-'+G.mm(g.heightM)+'.svg';document.body.append(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),500);}
async function copy(){const g=window.__TRUSS_CURRENT,c=window.__CANOPY_CURRENT;if(!g?.ok||!c)return;const button=$('copyTz'),old=button.textContent;try{await navigator.clipboard.writeText(tz(g,c));button.textContent='ТЗ скопировано ✓';}catch{button.textContent='Копирование недоступно';}setTimeout(()=>button.textContent=old,1600);}
function print(mode){document.body.dataset.print=mode;window.print();setTimeout(()=>delete document.body.dataset.print,600);}
window.addEventListener('afterprint',()=>delete document.body.dataset.print);
$('downloadSvg').addEventListener('click',download);$('printPdf').addEventListener('click',()=>print('welder'));$('printCalc').addEventListener('click',()=>print('calc'));$('copyTz').addEventListener('click',copy);
})();