(() => {
'use strict';
const $=id=>document.getElementById(id),G=window.TrussGeometry,C=window.CanopyPricing;
const INPUTS=['widthPosts','lengthPosts','visibleHeight','installType','coverage','materialMode','overhang','rise','autoRise','trussHeight','endFlat','cellStep','postsNeeded','existingPosts','beamsExisting','paint','delivery'];
const PRICE_KEY='kuzdvor-naves-prices-v1';
const PRICE_FIELDS=[
 ['tube25','25×25×1,5','₽/м'],['tube20','20×20×1,5','₽/м'],['tube30','30×30×2','₽/м'],['tube25web','25×25×1,5 для решётки','₽/м'],['tube40x20','40×20×2','₽/м'],['tube40x40','40×40×2','₽/м'],['tube80','80×80×3','₽/м'],
 ['poly','Поликарбонат 8 мм','₽/пог.м'],['connector','Соединитель 6 м','₽/шт'],['endProfile','Торцевой профиль 2,1 м','₽/шт'],['profnastil','Профнастил','₽/м²'],
 ['weld4m','Сварка фермы 4 м','₽/ферма'],['mountCover','Монтаж с покрытием','₽/м²'],['mountNoCover','Монтаж без покрытия','₽/м²'],['postConcrete','Столб — бетонирование','₽/шт'],['postPlate','Столб — закладная','₽/шт'],['paint','Покраска','₽/м²'],
 ['wire','Проволока + газ','₽/ферма'],['discs','Круги','₽/ферма'],['markup','Наценка полного навеса','%'],['ownerMount','Доля владельца из монтажа','₽/м²'],['separateMarkup','Наценка отдельной фермы','%']
];
const row=(a,b)=>'<div><dt>'+a+'</dt><dd>'+b+'</dd></div>';
const rub=n=>Math.round(Number(n)||0).toLocaleString('ru-RU')+' ₽';
const m=n=>G.fmt(Number(n)||0,2)+' м';
const m2=n=>G.fmt(Number(n)||0,2)+' м²';
const num=(id,fallback=0)=>{const v=Number($(id).value);return Number.isFinite(v)?v:fallback};
function loadPrices(){try{return C.mergePrices(JSON.parse(localStorage.getItem(PRICE_KEY)||'{}'));}catch{return C.mergePrices({});}}
function savePrices(){const x={};PRICE_FIELDS.forEach(([k])=>{const el=$('price-'+k),v=Number(el?.value);if(Number.isFinite(v)&&v>=0)x[k]=v;});try{localStorage.setItem(PRICE_KEY,JSON.stringify(x));}catch{}return C.mergePrices(x);}
function buildPriceSettings(){const p=loadPrices();$('priceSettings').innerHTML=PRICE_FIELDS.map(([k,label,unit])=>'<label class="field"><span>'+label+', '+unit+'</span><input id="price-'+k+'" type="number" min="0" step="'+(unit==='%'?'1':'10')+'" value="'+p[k]+'" inputmode="decimal"></label>').join('');PRICE_FIELDS.forEach(([k])=>$('price-'+k).addEventListener('input',()=>{savePrices();render()}));}
function syncRise(){const recommended=Math.round(num('widthPosts',3.4)*1000/6);$('riseHint').textContent='Рекомендуемый: '+recommended+' мм (ширина по столбам ÷ 6)';if($('autoRise').checked)$('rise').value=recommended;}
function rawInput(){const p=loadPrices(),lengthM=num('lengthPosts',8.4);return{widthPostsM:num('widthPosts',3.4),lengthM,visibleHeightM:num('visibleHeight',2.1),installType:$('installType').value,coverage:$('coverage').value,materialMode:$('materialMode').value,overhangMm:num('overhang',150),riseMm:num('rise',567),heightMm:num('trussHeight',250),endFlatMm:num('endFlat',300),cellStepMm:num('cellStep',400),trussCount:C.autoTrussCount(lengthM,p),postsNeeded:$('postsNeeded').checked,existingPosts:num('existingPosts',0),beamsExisting:$('beamsExisting').checked,paint:$('paint').checked,delivery:num('delivery',0)}}
function renderCut(g,c){const q=c.trussCount,rows=[['P1','Верхний пояс',g.chordProfile,G.mm(g.topCircle.length),1,q,'дуга'],['P2','Нижний пояс',g.chordProfile,G.mm(g.lowerTotalM),1,q,'дуга + прямые края'],['V','Торцевая стойка',g.webProfile,G.mm(g.endPostM),2,2*q,'90°']];g.diagonals.forEach(d=>rows.push(['D'+d.index,'Диагональ '+d.index,g.webProfile,G.mm(d.lengthM),1,q,G.fmt(d.angleDeg,1)+'°']));$('cutTableBody').innerHTML=rows.map(r=>'<tr>'+r.map(v=>'<td>'+v+'</td>').join('')+'</tr>').join('');}
function renderGeometry(g,c){$('summaryList').innerHTML=[row('Ширина по столбам',m(g.widthPostsM)),row('Ширина фермы',m(g.widthM)),row('Подъём дуги',G.mm(g.riseM)+' мм'),row('Высота фермы',G.mm(g.heightM)+' мм'),row('Верхняя дуга',G.mm(g.topCircle.length)+' мм'),row('Нижний пояс',G.mm(g.lowerTotalM)+' мм'),row('Ферм',c.trussCount+' шт'),row('Фактический шаг ферм',c.trussCount>1?G.fmt(c.lengthM/(c.trussCount-1),2)+' м':'—')].join('');$('compositionList').innerHTML=[row('Пояса',g.chordProfile),row('Решётка',g.webProfile),row('Торцевые стойки','2 × '+G.mm(g.endPostM)+' мм'),row('Диагонали','D1…D'+g.diagonalCount),row('Линий лаг',c.lagLines),row('Шаг лаг по дуге',G.fmt(c.lagStep*100,1)+' см'),row('Столбов нужно',c.totalPosts+' шт'),row('Новых столбов',c.newPosts+' шт')].join('');}
function renderClient(g,c){const valid=!c.coverageData.warning;$('totalPrice').textContent=valid?rub(c.total):'Нужна ручная проверка';const notes=[...c.warnings];$('resultStatus').textContent=notes.length?notes.join(' '):'РАСЧЁТ ДОПУСТИМ';$('resultStatus').classList.toggle('has-warning',notes.length>0);$('clientSummary').innerHTML=[row('Размер',G.fmt(g.widthPostsM,2)+' × '+G.fmt(c.lengthM,2)+' м'),row('Площадь',m2(c.area)),row('Покрытие',c.coverage),row('Ферм',c.trussCount+' шт'),row('Опоры','нужно '+c.totalPosts+', есть '+c.existingPosts+', новых '+c.newPosts),row('Продольные балки',c.beamsExisting?'уже есть':'изготовить 2 шт'),row('Цена без доставки',rub(c.priceNoDelivery)),row('Доставка',rub(c.delivery))].join('');}
function renderFinance(c){$('ownerSummary').innerHTML=[row('Расчётная база',rub(c.base)),row('Фактические расходы',rub(c.actualExpenses)),row('Наценка',rub(c.markup)),row('Твоя доля с монтажа',rub(c.ownerMount)),row('Прибыль до налогов',rub(c.profit)),row('Маржа',G.fmt(c.margin,1)+'%'),row('Металл',rub(c.metalCost)),row('Покрытие + фурнитура',rub(c.coverageCost+c.fittingsCost)),row('Сварка ферм',rub(c.weld)),row('Монтаж',rub(c.mount+c.postMount)),row('Покраска',rub(c.paintCost))].join('');$('trussPriceSummary').innerHTML=[row('Себестоимость без покраски',rub(c.oneTruss.cost)),row('Цена клиенту без покраски',rub(c.oneTruss.priceNoPaint)),row('Прибыль без покраски',rub(c.oneTruss.profitNoPaint)),row('Покраска одной фермы',rub(c.oneTruss.paint)),row('Цена клиенту с покраской',rub(c.oneTruss.pricePaint)),row('Прибыль с покраской',rub(c.oneTruss.profitPaint))].join('');}
function renderMaterials(c){$('metalTotal').textContent='Металл: '+rub(c.metalCost);$('materialsTableBody').innerHTML=c.materialRows.map(x=>'<tr><td>'+x.name+'</td><td>'+G.fmt(x.used,2)+' м</td><td>'+x.sticks+'</td><td>'+G.fmt(x.buy,0)+' м</td><td>'+rub(x.cost)+'</td><td>'+x.note+'</td></tr>').join('');const cards=[];if(c.coverage==='Поликарбонат'){const d=c.coverageData,parts=Object.entries(d.buyCounts).filter(([,v])=>v).map(([k,v])=>v+' × '+k+' м').join('; ')||'—';cards.push(['Поликарбонат','Полос: '+d.strips+' шт × '+G.fmt(d.coverArcM,2)+' м','Купить: '+parts+' = '+G.fmt(d.buyMeters,0)+' пог.м',rub(c.coverageCost)]);cards.push(['Фурнитура','Соединители 6 м: '+d.connectors+' шт','Торцевые профили: '+d.endProfiles+' шт',rub(c.fittingsCost)]);}else if(c.coverage==='Профнастил'){const d=c.coverageData;cards.push(['Профнастил','По дуге: '+d.sheetsAcross+' лист.','Частей: '+d.totalParts+' × '+G.fmt(d.partLength,2)+' м',rub(c.coverageCost)]);}else cards.push(['Покрытие','Без покрытия','Кровельные материалы не считаются','0 ₽']);cards.push(['Лаги','Линий: '+c.lagLines,'Схема закупки: '+c.lagsSticks+' хлыстов 6 м',G.fmt(c.lagUsedM,2)+' м используется']);cards.push(['80×80×3','Балок: '+c.beamCount+'; новых столбов: '+c.newPosts,'Купить: '+c.tube80Sticks+' хлыстов 6 м',G.fmt(c.beamPostUsedM,2)+' м используется']);$('coverageCut').innerHTML=cards.map(x=>'<article class="cut-card"><b>'+x[0]+'</b><span>'+x[1]+'</span><span>'+x[2]+'</span><strong>'+x[3]+'</strong></article>').join('');}
function render(){syncRise();const raw=rawInput(),prices=loadPrices(),g=G.compute(raw);window.__TRUSS_CURRENT=g;if(!g.ok){$('geometryWarning').hidden=false;$('geometryWarning').textContent=g.errors.join(' ');$('drawingStatus').textContent='проверьте размеры';$('trussSvg').innerHTML='<text x="600" y="300" text-anchor="middle" fill="#9b3c2d" font-size="24">Проверьте геометрию фермы</text>';$('totalPrice').textContent='—';return;}const c=C.compute(raw,g,prices);window.__CANOPY_CURRENT=c;g.trussCount=c.trussCount;const diff=Math.abs(num('rise')-g.recommendedRiseMm),warnings=[];if(diff>=15)warnings.push('Подъём отличается от рекомендации 1/6 ширины: '+Math.round(g.recommendedRiseMm)+' мм.');warnings.push(...c.warnings);$('geometryWarning').hidden=warnings.length===0;$('geometryWarning').textContent=warnings.join(' ');$('drawingStatus').textContent='готово';window.TrussDrawing.render($('trussSvg'),g);renderGeometry(g,c);renderCut(g,c);renderClient(g,c);renderFinance(c);renderMaterials(c);}
INPUTS.forEach(id=>{const el=$(id);if(!el)return;el.addEventListener('input',()=>{if(id==='rise'&&document.activeElement===$('rise'))$('autoRise').checked=false;render()});el.addEventListener('change',render);});
$('resetDefaults').addEventListener('click',()=>{$('widthPosts').value='3.4';$('lengthPosts').value='8.4';$('visibleHeight').value='2.1';$('installType').value='Бетонирование';$('coverage').value='Поликарбонат';$('materialMode').value='Авто';$('overhang').value='150';$('autoRise').checked=true;$('trussHeight').value='250';$('endFlat').value='300';$('cellStep').value='400';$('postsNeeded').checked=true;$('existingPosts').value='0';$('beamsExisting').checked=false;$('paint').checked=true;$('delivery').value='0';render()});
$('resetPrices').addEventListener('click',()=>{try{localStorage.removeItem(PRICE_KEY)}catch{}buildPriceSettings();render()});
$('trussForm').addEventListener('submit',e=>e.preventDefault());buildPriceSettings();window.TrussApp={render,rawInput,loadPrices};render();
})();